steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker' # Uses the Docker builder provided by Google Cloud Build
    id: 'Build Image'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-python-app:latest', # Tag as latest
      '.' # Use the current directory (where Dockerfile is) as the build context
    ]

# The 'images' section tells Cloud Build to push these images to Artifact Registry 
# after all steps above complete successfully.
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-python-app:latest'
  
options:
  logging: CLOUD_LOGGING_ONLY